//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BareuEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Adwat_bureauEntities : DbContext
    {
        public Adwat_bureauEntities()
            : base("name=Adwat_bureauEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<DiplomaUniversityTable> DiplomaUniversityTable { get; set; }
        public virtual DbSet<Lawyer> Lawyer { get; set; }
        public virtual DbSet<СourtСasesTable> СourtСasesTable { get; set; }
    }
}
